/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scheduler_process;

import java.awt.Point;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmed
 */
public class Scheduler extends javax.swing.JFrame {

    /**
     * Creates new form Scheduler
     */
        private FCFS fc=new FCFS();     private SJFNon sjn =new SJFNon(); 
        private PriorityNon priN=new PriorityNon();     private RoundRobin RR=new RoundRobin();
        private PriorityPre priP=new PriorityPre();     private SJFPre sjp=new SJFPre();
    private Vector<Process> vecProcess=new  Vector<>();
    private Vector<Float> TimeProcess=new  Vector<>();
    private int indexSelected;  private int counter=0;//use to count no of process that you add
    private int sizeProcess;
    DefaultTableModel  model;

    
    
    public Scheduler() {
        initComponents();
        setDefaultCloseOperation(Scheduler.DISPOSE_ON_CLOSE); 
        
    }
    public Scheduler(int msg,int noProcess) {
      
        sizeProcess=noProcess;
        if(msg==0) {fc.setNoProcess(noProcess); 
        }
        else if(msg==1) {sjn.setNoProcess(noProcess); 
        }
        else if(msg==2) {sjp.setNoProcess(noProcess); 
        }
        else if(msg==3) {priN.setNoProcess(noProcess);}
        else if(msg==4) {priP.setNoProcess(noProcess);}
        else if(msg==5) {RR.setNoProcess(noProcess);
        }
         indexSelected=msg;
           initComponents();
            setDefaultCloseOperation(Scheduler.DISPOSE_ON_CLOSE); 
         if(msg==3 || msg==4)
         {

             PriorityField.setVisible(true);
             PriorityLabel.setVisible(true);
             QuntumField.setVisible(false);
             QuantumLabel.setVisible(false);
         }
         else if(msg==5)
         {
              QuantumLabel.setVisible(true);
              QuntumField.setVisible(true);
              PriorityField.setVisible(false);
             PriorityLabel.setVisible(false);
              
         }
         else{
            QuantumLabel.setVisible(false);
            QuntumField.setVisible(false);
            PriorityField.setVisible(false);
            PriorityLabel.setVisible(false);   
         }
         disable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NameProcess = new javax.swing.JTextField();
        BurstProcess = new javax.swing.JTextField();
        ArrivalProcess = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        CalcButton = new javax.swing.JButton();
        QuntumField = new javax.swing.JTextField();
        QuantumLabel = new javax.swing.JLabel();
        PriorityField = new javax.swing.JTextField();
        PriorityLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        WaitingField = new javax.swing.JTextField();
        GanttPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        setLocation(new java.awt.Point(40, 0));
        setMinimumSize(new java.awt.Dimension(1270, 629));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data of Process", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Name of process");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Burst of process");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Arrival of process");

        AddButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        CalcButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CalcButton.setText("calculate & Draw");
        CalcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcButtonActionPerformed(evt);
            }
        });

        QuantumLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        QuantumLabel.setText("Quntum time");

        PriorityLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PriorityLabel.setText("Priority number");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                                    .addComponent(QuantumLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ArrivalProcess, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                        .addComponent(QuntumField))
                                    .addComponent(BurstProcess, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(194, 194, 194)
                                .addComponent(CalcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PriorityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PriorityField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NameProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriorityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PriorityField))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BurstProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArrivalProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuntumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuantumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton)
                    .addComponent(CalcButton))
                .addGap(31, 31, 31))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Gantt Chart & waiting time"));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Avg waiting time =");

        WaitingField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        GanttPanel.setBackground(new java.awt.Color(102, 102, 255));
        GanttPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gantt Chart", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel6.setText("jLabel5");

        javax.swing.GroupLayout GanttPanelLayout = new javax.swing.GroupLayout(GanttPanel);
        GanttPanel.setLayout(GanttPanelLayout);
        GanttPanelLayout.setHorizontalGroup(
            GanttPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GanttPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GanttPanelLayout.setVerticalGroup(
            GanttPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GanttPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WaitingField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1010, Short.MAX_VALUE))
            .addComponent(GanttPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WaitingField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GanttPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Table of process", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of process", "Burst of process", "Arrival of process", "Priority of Process"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
                // TODO add your handling code here:
                counter++;
                if(counter<=sizeProcess){
               
                String name; float ar=0; float bur=0;   int prio=0;
                
                try{
                    name=NameProcess.getText();
                ar=Float.parseFloat(ArrivalProcess.getText());
                bur=Float.parseFloat(BurstProcess.getText());

                if(indexSelected==0){
                fc.addProcess(new Process(name,bur,ar));
                model= (DefaultTableModel) jTable1.getModel();
                 model.addRow(new Object[]{NameProcess.getText(),BurstProcess.getText(),ArrivalProcess.getText()});
                }
                else if(indexSelected==1){
                   sjn.addProcess(new Process(name,bur,ar));
                   model= (DefaultTableModel) jTable1.getModel();
                   model.addRow(new Object[]{NameProcess.getText(),BurstProcess.getText(),ArrivalProcess.getText()});
                }
                else if(indexSelected==2){
                   sjp.addProcess(new Process(name,bur,ar));
                   model= (DefaultTableModel) jTable1.getModel();
                    model.addRow(new Object[]{NameProcess.getText(),BurstProcess.getText(),ArrivalProcess.getText()});
                }                
                else if(indexSelected==3){
                    prio=Integer.parseInt(PriorityField.getText());
                    priN.addProcess(new Process(name,bur,ar,prio));
                    model= (DefaultTableModel) jTable1.getModel();
                    model.addRow(new Object[]{NameProcess.getText(),BurstProcess.getText(),ArrivalProcess.getText(),PriorityField.getText()});
                }
                else if(indexSelected==4){
                    prio=Integer.parseInt(PriorityField.getText());
                     priP.addProcess(new Process(name,bur,ar,prio));
                     model= (DefaultTableModel) jTable1.getModel();
                     model.addRow(new Object[]{NameProcess.getText(),BurstProcess.getText(),ArrivalProcess.getText(),PriorityField.getText()});
                }                
                else if(indexSelected==5){
                     RR.addProcess(new Process(name,bur,ar));
                       model= (DefaultTableModel) jTable1.getModel();
                      model.addRow(new Object[]{NameProcess.getText(),BurstProcess.getText(),ArrivalProcess.getText()});
                }

                } catch (NumberFormatException e){                   
                   errorFrame err=new errorFrame();
                    err.setVisible(true);
                    err.setLabelText("Enter number not string or empty value");
                }
                NameProcess.setText("");   ArrivalProcess.setText("");   BurstProcess.setText("");
                PriorityField.setText("");                
             }
                
                
                else{
                    errorFrame err=new errorFrame();
                    err.setVisible(true);
                    err.setLabelText("sorry you enter no of process exceeded you select");
                }
                
                                   
    }//GEN-LAST:event_AddButtonActionPerformed
public void disable(){
    if(indexSelected==0) jTable1.removeColumn(jTable1.getColumnModel().getColumn(3));
    else if(indexSelected==1)jTable1.removeColumn(jTable1.getColumnModel().getColumn(3));
    else if(indexSelected==2) jTable1.removeColumn(jTable1.getColumnModel().getColumn(3));
    else if(indexSelected==3);
    else if(indexSelected==4);
    if(indexSelected==5)jTable1.removeColumn(jTable1.getColumnModel().getColumn(3));
}
    private void CalcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcButtonActionPerformed
        // TODO add your handling code here:
        String sc="";
        if(indexSelected==0){
            fc.print();
            sc=String.valueOf(fc.avgWaitingTime());
          vecProcess=fc.getSequenceProcess();
           TimeProcess=fc.getTimeLine();
        }
        else if(indexSelected==1){
            sjn.print();
          sc=String.valueOf(sjn.avgWaitingTime());
          vecProcess=sjn.getSequenceProcess();
           TimeProcess=sjn.getTimeLine();
        }
        else if(indexSelected==2){
            sjp.print();
          sc=String.valueOf(sjp.avgWaitingTime());
          vecProcess=sjp.getSequenceProcess();
           TimeProcess=sjp.getTimeLine();
        }        
        else if(indexSelected==3){
            priN.print();
          sc=String.valueOf(priN.avgWaitingTime());
          vecProcess=priN.getSequenceProcess();
           TimeProcess=priN.getTimeLine();            
        }
        else if(indexSelected==4){
            priP.print();
          sc=String.valueOf(priP.avgWaitingTime());
          vecProcess=priP.getSequenceProcess();
           TimeProcess=priP.getTimeLine();
        }          
        else if(indexSelected==5){
            int qu=Integer.parseInt(QuntumField.getText());
            RR.setQuantumTime(qu);
            RR.print();
          sc=String.valueOf(RR.avgWaitingTime());
          vecProcess=RR.getSequenceProcess();
           TimeProcess=RR.getTimeLine(); 
           
        }
        WaitingField.setText(sc);
        JLabel newLabel=new JLabel(String.valueOf(TimeProcess.get(0))); int x=10;
        newLabel.setBounds(x,50, 30, 30);  newLabel.setVisible(true);  GanttPanel.add(newLabel);
        for(int i=0;i<vecProcess.size();i++){
            JTextField newField=new JTextField(vecProcess.get(i).getName());
            int width=(int)((TimeProcess.get(i+1)-TimeProcess.get(i))*30);
            newField.setBounds(x, 20, width,30);
             JLabel newLabel2=new JLabel(String.valueOf(TimeProcess.get(i+1)));
                 x+=width;
             newLabel2.setBounds(x, 50,30,30);
             newLabel2.setVisible(true); newField.setVisible(true);
              GanttPanel.add(newField);
              GanttPanel.add(newLabel2);
        }

        
    }//GEN-LAST:event_CalcButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scheduler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField ArrivalProcess;
    private javax.swing.JTextField BurstProcess;
    private javax.swing.JButton CalcButton;
    private javax.swing.JPanel GanttPanel;
    private javax.swing.JTextField NameProcess;
    private javax.swing.JTextField PriorityField;
    private javax.swing.JLabel PriorityLabel;
    private javax.swing.JLabel QuantumLabel;
    private javax.swing.JTextField QuntumField;
    private javax.swing.JTextField WaitingField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}

